services:
  prisma-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: MdP9QmSZqwqqp4xwk36vH9Q4c
      POSTGRES_DB: odysseus-prisma
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  typesense:
    image: typesense/typesense:29.0
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense:/data
    command: 
      ["--data-dir", "/data", "--api-key", "${TYPESENSE_API_KEY:-xyz}"]


  init-search:
    profiles: ["init"]
    build:
      context: ./data/search
    depends_on:
      - typesense
    volumes:
      - ./data/raw-data:/app/raw-data
      - ./data/search:/app/search
      
volumes:
  postgres-data: